### ISSUE TITLE
possible dupe bug

### ISSUE THREAD

**Issue by kreezxil** [Bartz24/SkyResources#1]
With one character I mined away the starting sand block, and then I switched characters, when that new 2nd character logged on, the previously mined away sand block was restored. The world did not revert however, because with the first character I put the extra sand block in a corner and put a cactus on it and also in an opposing corner. The new 2nd character saw the extra sand block with the cactus on top and the opposing corner cactus.

**Comment by Bartz24** [comment]
Should be fixed in the next version.  Let me know if it works when it's released (tomorrow morning).

**Comment by Bartz24** [comment]
Use version 0.4.1 as 0.4 probably won't work.
