### ISSUE TITLE
Crash with Forestry v204 and above

### ISSUE THREAD

**Issue by KAfable** [Bartz24/SkyResources#101]
Crash log here:

https://hastebin.com/hiqigageyi.sql

I think Forestry has recently changed how some of its internals are organized, and giving some compat issues for multiple mods going beyond Foresty v5.6.0.201, just wanted to give a heads up in case you wanted to update Sky Resources.

**Comment by Bartz24** [comment]
You're on Sky Resources 2.0.23, but there's now 2.1.0 and 2.1.1 that have fixed that crash. Check for the latest version first :D

**Comment by KAfable** [comment]
Ah gotcha, it was still marked as beta instead of a release on Curse, I'll make a note to update, thanks!
