### ISSUE TITLE
End Portal cant make.....

### ISSUE THREAD

**Issue by ghost** [Bartz24/SkyResources#106]
Hello, I have a little problem with the end portal. we have a server by making it possible for every player to create their own world. However, we now have the problem that it is only feasible on one single to create the end portal.

I have already looked in the configs, but I find no solution for this ... is there a solution that you can do in other worlds, the end portal? our servers are running on spongeforge, if that helps.

Minecraft version 1.12.2
ModPack: Modern Skyblock 2
Version: 2.7.2
ModVersion: skyresources-2.1.2

**Comment by TheLimePixel** [comment]
What's the issue here? You didn't really specify what the issue is.

**Comment by Bartz24** [comment]
The end portal is locked to only work in dimension id 0
Maybe I should remove that...

**Comment by Bartz24** [comment]
Removed dimension check
