### ISSUE TITLE
[1.12.2] Crash on dedicated server 

### ISSUE THREAD

**Issue by yuanjie000** [Bartz24/SkyResources#108]
MC 1.12.2
skyresources-2.1.4& 2.1.3
[crash here](http://paste.ubuntu.com/26017306/)

**Comment by Whazaaaaa** [comment]
Having the same crash

**Comment by Alxandr** [comment]
https://minecraft.curseforge.com/projects/modern-skyblock-2/issues/441 same here

**Comment by Bartz24** [comment]
A hotfix has been released, just waiting for it to be approved on curse

**Comment by Alxandr** [comment]
How long does curse approval normally take?

**Comment by Bartz24** [comment]
It's up now, it took a while today for some reason

**Comment by Alxandr** [comment]
Great. Thanks :)
