### ISSUE TITLE
[Suggestion] Base Metals support

### ISSUE THREAD

**Issue by InkDragon** [Bartz24/SkyResources#11]
any chance we might see support for base metals?

**Comment by Bartz24** [comment]
most should be supported, but ill look at what's missing

**Comment by Bartz24** [comment]
im not adding nether ores unless i turn the nether into a void world too

**Comment by InkDragon** [comment]
Mercury is only one I was concerened with

**Comment by Bartz24** [comment]
that's a liquid though, kinda tough to do

**Comment by Bartz24** [comment]
well, ill add it
turns out it's not a liquid oddly
