### ISSUE TITLE
Guide for end portal multiblock structure?

### ISSUE THREAD

**Issue by bowmanjd** [Bartz24/SkyResources#115]
Are we supposed to know how to build the end portal structure, or is that intended to be a challenging guessing game? I am up to the challenge, yet wondered if something was missing from the guide.

**Comment by TheLimePixel** [comment]
"Multiblock Setup" is a hyperlink.

**Comment by bowmanjd** [comment]
Well, look at that. That is a whole lot easier than reading the source code! Thanks so much for your response (and sorry for my lack of observation skills!)
