### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by 0dikpah** [Bartz24/SkyResources#116]
[crash-2017-12-12_16.20.28-client.txt](https://github.com/Bartz24/SkyResources/files/1552113/crash-2017-12-12_16.20.28-client.txt)

Minercraft 1.12.2
Forge 14.23.1.2562
Skyresources-2.1.5

**Comment by brisingraerowing** [comment]
The issue is that you don't have anything that is oredicted as oreUranium.

[This line](https://github.com/Bartz24/SkyResources/blob/1.12-2.0/src/main/java/com/bartz24/skyresources/registry/ModCrafting.java#L590) needs to be under the if statement right below it.

**Comment by Bartz24** [comment]
Fixed
