### ISSUE TITLE
Crushed Netherrack has no uses when Draconic Evolution is not installed

### ISSUE THREAD

**Issue by MatthiasMann** [Bartz24/SkyResources#117]
And as such can't be put into a cauldron or in the rock cleaner.

Wouldn't it be better to either not generate it at all in this case - or add a recipe which is available even without other mods?

I'm using Sky Resources 2.1.5

**Comment by TheLimePixel** [comment]
Well, it can be used for Cobalt or Ardite Dust as well. They aren't in vanilla Tinker's, so you are going to need a mod like JAOPCA that adds them.

**Comment by MatthiasMann** [comment]
Yeah - but I only have tinkers and PlusTIC - no JAOPCA.
