### ISSUE TITLE
No recipe for Zinc ore in condenser

### ISSUE THREAD

**Issue by NiSiSuinegEht** [Bartz24/SkyResources#118]
As the title says, Zinc ore cannot be made with stone above the condenser, only zinc ingots with crystal fluid.  Checking through all the available Alchemical Ore Dusts it appears that Zinc and Chrome are the only two missing an ore recipe.

Sky Resources v2.1.5
Included in the Modern Skyblock 2 modpack v2.7.3.3

**Comment by TheLimePixel** [comment]
That's because there is no Zinc Ore in MSB2.
