### ISSUE TITLE
WaterExtractor Recipe not removed

### ISSUE THREAD

**Issue by Ardragos** [Bartz24/SkyResources#123]
I am currently working on a modpack and tried to remove the recipe for clay.
It worked for the normal WaterExtractor, but there is still the recipe for the compressedWaterExtractor and I am not able to remove it.
Tried it with the recipe for the cactus too, didn't work either.

**Comment by Bartz24** [comment]
The compressed water extractor is not a part of Sky Resources, sorry.
I can't do anything about that.
It's a part of Sky Compression
