### ISSUE TITLE
I accidentally your mod's Cauldron behaviour

### ISSUE THREAD

**Issue by asiekierka** [Bartz24/SkyResources#125]
I have a mod, [Charset Crafting](https://minecraft.curseforge.com/projects/charset-crafting), which adds its own improved, but entirely backwards-compatible, version of the Cauldron. One of the features it adds is Dyed Water, and dyeing items using it.

You have a mod, Sky Resources, which adds an aid for ore processing utilizing the Cauldron - in this particular case, turning dirty ores into their clean versions, such as lapis lazuli.

Lapis Lazuli happens to be a dye, which is then dropped - after cleaning with water - into the Cauldron.

...I think we both can see where this is going.

There's multiple solutions:

- Your mod could add an option which adds the cleaned metal/ingot/dye directly into the player's inventory or drops it below the player, as opposed to dropping it into the cauldron.
- My mod could add a tweak which prevents Lapis Lazuli from being treated as a dye, instead adding a crushed variant of it acting as Blue Dye. (In fact, I was already planning this - for other reasons!)
- My mod could add (and will add) an option which makes the cauldron not override vanilla's.
- I could add a special API which lets you mark EntityItems as "not usable" by my cauldron - as I already plan to mark crafting results of my own cauldron as such. You could then implement it in your mod.

I believe that, for the freedom of pack makers, implementing multiple of those solutions as configurable options would be most ideal. Some of them might want to, say, keep my cauldron as the default cauldron, while also supporting Sky Resources.

I'm open for discussion regarding this.

**Comment by Bartz24** [comment]
I've changed it so that results spawn 1 above the cauldron.
If this still won't fix the issue (based on your item detection) I'll add configs to spawn it at the player's pos. I don't want to clutter the config too much.

**Comment by asiekierka** [comment]
If it falls into the cauldron, it will collide - I detect collisions with the cauldron's insides.
