### ISSUE TITLE
Eio integration 

### ISSUE THREAD

**Issue by tyler489** [Bartz24/SkyResources#128]
Can you add support for enderio metals. And prehaps some machines that use said  metals. Like casings/combustion etc.

**Comment by Bartz24** [comment]
This is planned for the future, but not until some changes to the mod occur.
Other materials like botania and thaumcraft are also planned for the casing system!

**Comment by Bartz24** [comment]
I'm going to close this as it's already in Varying Machina and these changes will take effect on Sky Resources once it is moved to an addon for VM
