### ISSUE TITLE
Need way to disable April Fools garbled text.

### ISSUE THREAD

**Issue by macrosblackd** [Bartz24/SkyResources#134]
While this is funny the first time you open the guide, it makes mod packs using this mod unplayable due to being unable to actually read anything.

**Comment by valerian** [comment]
I just started playing Modern Skyblock 3 with friends today, and it's extremely annoying

**Comment by valerian** [comment]
I tried to recompile a fixed version, but being not very familiar with Java compilation and this package being a bit old I couldn't manage to do it, I guess I will have to wait for tomorrow to start playing.
