### ISSUE TITLE
Island resetted itself

### ISSUE THREAD

**Issue by DaroMoon** [Bartz24/SkyResources#135]
warping back to my island using the draconic dislocator caused me to go back to spawn before you create an island, its kinda hard to show this since it deleted all my stuff since it treated it as if i just spawned a new world, or having any idea how it happened.

minecraft 1.12.2
forge 14.23.2618
sky resources 2.2.3

**Comment by Bartz24** [comment]
This is not a sky resources issue. Void island control recently added some admin commands to reassign players back on islands
