### ISSUE TITLE
Snow layer loophole

### ISSUE THREAD

**Issue by MattJohns** [Bartz24/SkyResources#136]
It's possible to 'duplicate' snow by placing a snow block then right clicking to get 8 snowballs back (only 4 are used to create the snow block in the first place).

This means there is no incentive to collect fallen snow layers or build a snowman.  Instead you just lay out a row of snow blocks and right click them into snowballs.

Would you consider changing it so that there is only 50% of a snowball when you right click a layer (or a stack of layers)?

I tried fixing it in my modpack by changing the snow block recipe so it required 8 snowballs.  But that makes it really laborious to create snow blocks and also requires a crafting table rather than the 2x2 personal table.

**Comment by Bartz24** [comment]
Not a bug. It's been left as a "feature" to provide a backup if the snow golem dies
