### ISSUE TITLE
[0.8.7] When creeper explodes near minifreezer, server crashes

### ISSUE THREAD

**Issue by kreezxil** [Bartz24/SkyResources#14]
Issue:  Sky Resources 0.8.7 Beta crashes dedicated Forge 1.10.2 build 2014 when creeper explodes and takes out a minifreezer in the process

crash report:
https://gist.github.com/42645a3ed830585083c2f21632323539

fml server latest:
https://gist.github.com/827f17b6e0ea58188952f491f186f6c2

**Comment by Bartz24** [comment]
Fixed
