### ISSUE TITLE
Combustion Heater does wrong recipes

### ISSUE THREAD

**Issue by codewarrior0** [Bartz24/SkyResources#140]
skyresources-2.3.1

Previously, the Combustion Heater would only perform recipes when given a redstone pulse. Attaching a lever and flipping it on would only do recipes once. Now, the Combustion continues to do recipes for as long as it has a high redstone signal.

While this would normally be a neat feature since you don't need a redstone clock to continuously craft with it, there is one important consequence:

After creating Redstone using Blaze Powder and Gunpowder, the Combustion immediately drops the remaining stacks of powder in the world ~~with random velocities~~ *inside the casing block*. The next tick, it will *sometimes* find that only the Gunpowder stack is still in the chamber, and turn the Gunpowder to Blaze Powder when what it should have done is continue to craft Redstone using both the Blaze Powder and Gunpowder.

~~One possible resolution is to drop the remaining stacks with no velocity, by setting the `motion[X,Y,Z]` fields of the EntityItem to zero. [I believe this is the relevant code.](https://github.com/Bartz24/SkyResources/blob/1.12-2.0/src/main/java/com/bartz24/skyresources/technology/item/ItemCombustionHeater.java#L315-L325)~~

**Comment by codewarrior0** [comment]
Aha! I did some debugging and found this has nothing to do with the item velocity; rather, it's because the Combustion will spawn the resulting and remaining items in the center of the combustion's casing block itself, rather than the center of the chamber above the casing.

**Comment by Bartz24** [comment]
Thanks for noticing that.
I just implemented these changes
