### ISSUE TITLE
Crash When Forestry Bees Disabled

### ISSUE THREAD

**Issue by TwilightPSN** [Bartz24/SkyResources#146]
I am currently building a pack with Sky Resources 2 in it and have the issue where i disable the bees from Forestry and the pack will crash on load. Once I enabled them again, it loads just fine. Is there a way to possibly add an option to disable bees integration for when you don't want them used?  Attaching the Crash Report.
[crash-2018-07-16_19.44.53-client.txt](https://github.com/Bartz24/SkyResources/files/2199698/crash-2018-07-16_19.44.53-client.txt)

**Comment by TheLimePixel** [comment]
All the integrations are already configurable.

**Comment by TwilightPSN** [comment]
machines themselves are configurable but not the ability to disable an integration

**Comment by Bartz24** [comment]
I'll release a fix today adding the ability to turn off individual mod plugin support

**Comment by TwilightPSN** [comment]
thanks alot @Bartz24

**Comment by Bartz24** [comment]
Just released the new version
