### ISSUE TITLE
Potential Addon/metal system improvement

### ISSUE THREAD

**Issue by DrDarkfire** [Bartz24/SkyResources#147]
Hiya, so I was planning on making a mod that adds items for me to add TAIGA support to my pack via crafttweaker. Is there a chance support for this mod could get built in, or even more extreme a custom ore dust system where we give you the color scheme and some numbers, and your mod adds them. I think this would benefit lots of pack devs that want to use this mod in their pack and not bug you for support for xyz mods. If this capability exists within your mod and doesn't require me to make my own mod, excuse my ignorance.

**Comment by Bartz24** [comment]
Sorry. Implementing a way to add custom alchemical ore dust would be too messy for Sky Resources 2.
Version 3 of the mod is currently being worked on (at a slow pace) where this would be much easier and doable.

You could try to see if JAOPCA works with the items you need, as JAOPCA has support for adding the alchemical ore dusts.
