### ISSUE TITLE
Flint is converted directly into blaze powder bypassing gunpowder

### ISSUE THREAD

**Issue by Keltas** [Bartz24/SkyResources#148]
1 flint converts directly into 9 blaze powder for me. I seem to hear two explosions 1 immediately after the other when applying redstone signal, as if conversion from 1 flint to 3 gunpowder was immediately followed by 3 gunpowder to 9 blaze powder. This makes it really hard to get gunpowder for me. I sometimes am able to make an impulse short enough to get some gunpowder by using a lever rather than button, but it is very inconsistent. I've tested it using a curse client with just JEI 1.12.2-4.11.0.204 and Sky Resources 2.3.3 using iron combustion heater and frame. Forge version 14.23.4.2739. 

Is this a bug or I just don't get how you are supposed to get gunpowder? I seem to vaguely recall that when I used it before, every redstone signal application used to cause just one explosion at a time.

**Comment by TheLimePixel** [comment]
This was fixed in the latest Sky Resources version.

**Comment by Bartz24** [comment]
keltas just said he was using the latest 2.3.3
I'll look into it

**Comment by TheLimePixel** [comment]
Huh, I thought you had fixed that.
