### ISSUE TITLE
Smart Combustion ignores Muffler

### ISSUE THREAD

**Issue by Wuumaster** [Bartz24/SkyResources#157]
As mentioned in the Discord channel, some quick experimentation shows that the Combustion Heater ignores Muffler traits when using the Smart Combustion Controller. Manually activating combustion via lever/button works as silently as expected, however, even while the SCC is part of the multiblock.

Figured I'd mention this here for the record. :)

**Comment by Bartz24** [comment]
Fixed in 2.3.9

**Comment by iRiceCrispy** [comment]
I do not believe this is fixed. I am playing on Enigmatica 2 Expert Skyblock, which uses Sky Resources 2 v2.3.9. There's still an explosion sound when using a Smart Combustion Controller with a casing that has MUFFLER.
