### ISSUE TITLE
(Crosspost) Sky Resources Cauldron Cleaning breaks with Inspirations Cauldron

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [Bartz24/SkyResources#163]
(Crosspost of KnightMiner/Inspirations#122)

There's currently a compatibility issue with Inspirations (as well as probably any other mods that modify / add Cauldrons) where whenever the Cauldron is supposed to lose water after for example cleaning gems with it, the amount of water in the Cauldron doesn't actually go down (neither visually nor physically), but the Cauldron is still considered "empty" at a certain point and you're no longer able to clear stuff with it until you take an empty bucket and then empty and refill the cauldron.

There's more info in the original issue if you need anything more, KnightMiner actually found the source of the problem, as well ^^

**Comment by Bartz24** [comment]
Fixed in 2.3.9
