### ISSUE TITLE
Capability injection issue, noticed with Nuclearcraft

### ISSUE THREAD

**Issue by JulianSchutsch** [Bartz24/SkyResources#164]
Minecraft 1.12.2, Forge 14.23.5.2838
Crashlog: https://pastebin.com/vAbYN0ZR

I reported this to Turbodiesel(Nuclearcraft), but he pointed me to you:
https://github.com/turbodiesel4598/NuclearCraft/issues/544

with this hint: https://github.com/Bartz24/SkyResources/blob/1.12-2.0/src/main/java/com/bartz24/skyresources/base/tile/TileCasing.java#L158-L159

**Comment by DestinyPlayer** [comment]
Can confirm the same crash
https://paste.dimdev.org/orabodahuf.rb - crash log
http://prntscr.com/o52wej - modpack
Forge - 14.23.5.2838

**Comment by ghost** [comment]
Same crash here

**Comment by BasieBrinkie** [comment]
+1

**Comment by Bartz24** [comment]
Fixed in 2.3.9
