### ISSUE TITLE
[Bug] - Crafttweaker removal of catalyst unsuccessful

### ISSUE THREAD

**Issue by BasieBrinkie** [Bartz24/SkyResources#165]
Sky Resources - 2.3.8
Crafttweaker - 4.1.19
Forge - 14.23.5.2838

When removing catalysts with `mods.skyresources.catalysts.remove(skyresources:alchemyitemcomponent:5>);` 
catalysts aren't being removed with this function.
The crafttweaker.log does display the following line of text:
> [INITIALIZATION][CLIENT][INFO] Removing catalyst value for Quartus Alchemical Dust

But in-game the catalyst still works with the original catalyst value in the alchemical fusion table.

BasieBrinkie

**Comment by Bartz24** [comment]
Fixed in 2.3.9
