### ISSUE TITLE
sky_resources2 cannot be cast to nc radiation

### ISSUE THREAD

**Issue by JackMeds** [Bartz24/SkyResources#166]
https://pastebin.com/B5cqh6n5
when i place any Casing ,the game crashed.
The author of NC does not think it is on his side
I can only rely on you. Please help me.
Version：
skyresources-2.3.8.jar
forge 2838

**Comment by BasieBrinkie** [comment]
#164

**Comment by Bartz24** [comment]
Fixed in 2.3.9
