### ISSUE TITLE
crashes when placing down stone casing or wood casing

### ISSUE THREAD

**Issue by raziel23x** [Bartz24/SkyResources#167]
I am currently in the process of making a skyblock modpack and every time so far every one of my test worlds crash the second i place a casing down so far i only have tried to place down the wood casing and the stone casing and each time the game just crashes

crash report
crash-2019-07-16_01.03.44-server.txt
https://paste.dimdev.org/enabemayoq.rb

here is a copy of the modpack export in case you want to see whats going on
[New Skyblock-0.0.1.zip](https://github.com/Bartz24/SkyResources/files/3395411/New.Skyblock-0.0.1.zip)

**Comment by raziel23x** [comment]
okay when i disabled radiation in nuclearcrarft this fixed the crashing for some reason it is conflicting with this mod

**Comment by Bartz24** [comment]
Fixed in 2.3.9
