### ISSUE TITLE
1.0.0 Lapis Fluid produces cobalt shards and crashes game.

### ISSUE THREAD

**Issue by TacoMage** [Bartz24/SkyResources#18]
If you place clean Lapis crystal fluid in the world, it produces cobalt shards instead of lapis shards.

If you place clean or dirty lapis crystal fluid on top of an alchemical condensor to produce lapis, the game crashes when the game tries to convert the fluid into lapis.  Crash log attached.

[crash-2016-08-19_11.36.59-server.txt](https://github.com/Bartz24/SkyResources/files/427468/crash-2016-08-19_11.36.59-server.txt)

**Comment by TacoMage** [comment]
I just discovered that most of the molten fluids do this as well.  Does this fix apply to those or should I open a new bug report?

**Comment by Bartz24** [comment]
It might, but try it in 1.0.1 first.
