### ISSUE TITLE
Combustion Mechanic Overly Tedious

### ISSUE THREAD

**Issue by LucidCrux** [Bartz24/SkyResources#28]
The combustion mechanic sounds interesting on paper, but actually going through it in a game is incredibly tedious. It makes the sieving from Ex Nihilo (sp?) seem really fast in comparison.

I think there are at least two major issues.

First is the fact it needs broken and rebuilt each use. Later, you can use a piston to somewhat lessen this, but you still have to reposition yourself in a place you can throw things in, close it, then still access the base. It is quite awkward and cumbersome.

Second is single item creation. Alone, this might not be a problem. Throw in a recipe wait a second, get an item. But in unison with the above, it just amplifies the awkwardness. Not everything needs to be batchable in groups if there ends up being an alternate way to get said item very soon after (for example crystals from pure fluid) but if it is the only way (or only way for a long time) it needs to work in bulk. The two biggest examples are blaze powder and dirt early. Really, though, I think as a player it would be best if everything worked up to a stack of each ingredient, possibly even multiple stacks for single ingredient items. As long as nothing uses all the same ingredients, it should be very doable.

**Comment by Bartz24** [comment]
Here's the thing.

PROGRESSION.
You start with one that is very tedious, and then you can use a dropper on the iron combustion heater.
If there's a automatic dropper or something, that's even better.
If there's steel in the pack, you can get the steel heater, which runs on RF.

Metal creation does NOT require a crystal made in combustion every single time. Read the guide, there's a page for clean crystal fluid which explains a better method.

Multiple sets at a time will be coming later (either as an easy mode option, or late game)

It could be easily be automated with some type of dropper, a vacuum chest, a timer, maybe some redstone. Autocrafting with Refined Storage works great with this, too.

The way it is right now is the way it's going to be.

**Comment by LucidCrux** [comment]
You need to make clear that you can use a dropper for iron. Will a dropper work for steel also? I guess the fact it is a 'stone' item makes some sense afterward, but it isn't clear it can be something other than a solid block.

Also, yes, I said the crystal thing is okay since there is an alternative very quickly. Sorry if that was unclear. For some things though, it really isn't fun. I know that is a subjective thing, but when it goes much slower than sifting for some things, even mid/late game. I think you will have an issue finding popularity. People already complained about sifting and mods were made to speed it up and automate it.

Just something to consider. Again, it is subjective, but I almost quit the pack I am playing when I got to making a blaze block and I have no problem with sifting in ex nihilo. A single blaze block really isn't a big deal, but it was a sign of things to come. I can still only play in very short chunks if I have goal requiring items that need to use the mechanic, it gets boring and seems very artificially limiting.

Any alternatives to ex nihilo are good, so I'm just sharing my experience.

**Comment by Bartz24** [comment]
This is why I'm wanting to make an easy mode.

But, yeah, I'll put a hint to use a dropper.

**Comment by Bartz24** [comment]
Just know that things used to be much more tedious 2-3 months ago.  This isn't nearly as grindy in comparison.
