### ISSUE TITLE
Heat Source Info

### ISSUE THREAD

**Issue by LucidCrux** [Bartz24/SkyResources#30]
It would be nice if there was information about the heat given by various heat sources. Powered Heater says it provides a heat of 30, but without anything to compare that to, the info is pointless. The guide says jei lists the heat sources, but either this isn't implemented yet or doesn't work properly. I can find no 'heat sources' category when clicking recipes or uses for a torch for example.

**Comment by Bartz24** [comment]
I keep forgetting to add values in the default list.

The easiest way for getting heat sources in JEI is to find a category for recipes in Sky Resources, click the category to get access to all categories, and then scroll left or right on the categories.  Heat Sources  in JEI are a bit of a pain as most of the heat sources are blocks, but not items anymore in the new versions of MC.

**Comment by LucidCrux** [comment]
Hrm, figured it out now. Learned something new with JEI. I thought it would be a default category for any heat source. Also clicking the bar doesn't work, you have to click the category text. I suppose you could chalk this one up to a new 1.10 player.

It seems like there should be a way to link heat sources more explicitly though, similar to how the description category works and comes up naturally for relevant items like the blaze block. It does work as advertised though, so my bad.

**Comment by Bartz24** [comment]
Yeah, it's just more difficult for me as some blocks like fire, and lava, don't have an item form, which jei uses.  I'll find some way to do it.
