### ISSUE TITLE
Unused Dirty Gems

### ISSUE THREAD

**Issue by LucidCrux** [Bartz24/SkyResources#31]
Unusable dirty gems should not drop. The items are just trash. I know fairly little about minecraft mods, but if you can't exclude them at startup for some reason, then you should at least do a check on drop. Even if all you do is auto delete them, it would save players the hassle.

Also, I'll just put this here as it is similar. Crushed stone is also trash and simply clogs up inventory. Either make a use for it, drop sand or gravel instead, or just don't have it.

**Comment by Bartz24** [comment]
Unused gems and crystals will somehow be "banned", not drop, or something. It is something that has recently occurred to me when I was watching a lp.

**Comment by Bartz24** [comment]
Also, crushed stone will have a use for the mod itself, but right now, it can currently be used in ic2 to get stone dust.
