### ISSUE TITLE
Water Extractor automation

### ISSUE THREAD

**Issue by LucidCrux** [Bartz24/SkyResources#32]
Perhaps it simply hasn't been added yet and you have plans, but there needs to be a nicer mid/late alternative to the Water Extractor for clay or clay blocks. Ultimately, most mod players like automating or at least simplifying and bulk processing items. The water extractor doesn't allow for that at all.

**Comment by Bartz24** [comment]
It's not a top priority, but I'm going to do something to the recently added life infuser multiblock for automating life infusion.
