### ISSUE TITLE
Possible issues with condensing liquid metals

### ISSUE THREAD

**Issue by LucidCrux** [Bartz24/SkyResources#33]
I'm not positive this is an issue, I haven't done a lot of testing. It seemed like there was in issue with liquids condensing into an ingot if a fluid dropper above it was trying to drop a liquid. My setup was basically like the guide shows, but with torches instead of lava. It could have been that is was just taking a very long time because of that, but I don't think so.

I left iron to condense several times while I went afk. If I stuck an extra crystal in the crucible to try to get 2 ingots while I was gone, I never got one. After clearing the waiting liquid and letting the second batch drop, then going afk again, I always seemed to end up with my ingot.

My guess is that it has something to do with the 'no flowing liquid' logic and every time the dropper tried to drop on the already full block, it triggers a reset or something.

Right now, it is a minor issue, but later on when things are more automated, it could be a huge issue that backs everything up and stops production entirely.

**Comment by Bartz24** [comment]
Nope, it's just the torch takes a VERY LONG time. People were saying 20-30 min for 1 ingot, while it's 3-5 with lava.

I've setup a automatic metal system, and the dropper is fine.  It used to be a problem a couple months ago or something.

**Comment by Bartz24** [comment]
I have moved all the issues you've mentioned that I would do something about to the Things I'm Going to Do list

Thanks for all the input though.
Would have preferred if it was all in one issue, but I see why you didn't xD
