### ISSUE TITLE
A user of the Ultra Mini Omnia reported the following

### ISSUE THREAD

**Issue by kreezxil** [Bartz24/SkyResources#38]
[Icepick_Josh](https://minecraft.curseforge.com/members/Icepick_Josh)

I encountered a crash when clicking on a link in the Sky Resources guide. I didn't see anywhere else to post this. Stack trace at: [http://pastebin.com/10MQnjSu](http://pastebin.com/10MQnjSu)

**Comment by Bartz24** [comment]
might be because the jei code changed...looking into it
