### ISSUE TITLE
Island reset/leave suggestions

### ISSUE THREAD

**Issue by ghost** [Bartz24/SkyResources#40]
Will be possible when player do /platform reset clear area where present island is and create new island at same location? (Now is created new island at new location and old isnt deleted.)

Will be possible add question "Are you sure?" before reset island?

Cooldown between resets will be usefull too. (for example 1 minute, then 10 minutes, then hour, then 12 hours...)

When player leave island, delete area, then flag it as orphan - new island can be created here preferably.

Similar features are in the popular uSkyBlock bukkit plugin.

Please consider add these features. Thanks.

**Comment by Bartz24** [comment]
There's a couple reasons I don't have reset in the same area.

It was very laggy when as I was deleting a 500x500 area before(as clearing the whole area is important, not going to delete a 100x100 as the player can easily build outside of that)

And I would also have to delete the nether, adding a lot more time to delete an area.

An are you sure option will not be added as the player isn't going to type "/platform reset" on accident.

Cooldowns are pointless with resetting to a new area and the start of the snow/sand are tricky to do at first and I don't want to make people wait to be able to restart if they lose everything.
