### ISSUE TITLE
API: IslandLeaveEvent NPE

### ISSUE THREAD

**Issue by ghost** [Bartz24/SkyResources#41]
Im using yours API, but when try get island position of leaved island, got NPE because getIslandPosition() returns null.

My code:

<pre>
	@SubscribeEvent
	public void onIslandLeave(IslandLeaveEvent event) {
		Player player = Sponge.getServer().getPlayer(event.getPlayerUUID()).get();
		System.out.println("Player " + player.getName());
		System.out.println("Position " + event.getIslandPosition() );  <----  null object
        .......
</pre>

Console output:
<pre>
[09:38:52] [Server thread/INFO] [STDOUT]: [net.rebelgames.srbridge.SRBridge:onIslandLeave:141]: Player HunterzCZ
[09:38:52] [Server thread/INFO] [STDOUT]: [net.rebelgames.srbridge.SRBridge:onIslandLeave:142]: Position null
</pre>

IslandCreateEvent, IslandInviteEvent works without problem.

**Comment by Bartz24** [comment]
Looking into it soon

**Comment by Bartz24** [comment]
Fixed in next version.

Also, note that if a island pos is null after the next update, it means the player doesn't have an island :D (I think, been a while since I put it in)
