### ISSUE TITLE
Issues with fluid transfer and automation

### ISSUE THREAD

**Issue by cpeake9** [Bartz24/SkyResources#42]
Been playing with this mod on All the mods new skyblock pack. I wanted to attempt to automate the process of metal forming but encountered bugs making it impossible quickly. Namely: The purification vessel will accept liquids fine, however once the dirty liquid is finished processing it will somehow put clean fluid in the bottom tank preventing any fluids form being pulled or pushed.

http://prntscr.com/d5u0fn

**Comment by Bartz24** [comment]
based on the picture, the transfer pipe behind the vessel is connected, so it pipes the clean fluid back in. Disconnect that pipe and it will start working again :D
Not a bug on either mod.

**Comment by cpeake9** [comment]
While I can possibly see that it would be a good idea to prevent you from pumping clean fluids back into the purifier. Doing so seems to make it unuseable until broken and replaced. Not to mention there's no reason to be able to pump clean fluid in anyways.

**Comment by Bartz24** [comment]
Here's my thinking. The vessel isn't "smart" enough to determine if it's a valid fluid.  What I will do is make it so that the vessel "processes" the fluid by putting the same fluid on top.

**Comment by cpeake9** [comment]
That should fix the problem of having to break it and replace it. Sounds good. Baring ofc you add the ability to purify the liquid multiple times at some point.
