### ISSUE TITLE
Cauldron stealing items.

### ISSUE THREAD

**Issue by garath77** [Bartz24/SkyResources#47]
I'm posting this here because I don't remember ever seeing this issue in vanilla...

While using the cauldron to clean stone dust and dirty gems, several times I've accidentally 'cleaned' several vanilla items. The problem is, when you put them in the water in a cauldron, you don't get them back. Same thing has happened with an empty cauldron. Is this something that you can look into?

Thanks

**Comment by Bartz24** [comment]
Oh...that'll be fixed soon :)
