### ISSUE TITLE
Rock Crusher produces crushed stone out of nothing

### ISSUE THREAD

**Issue by medsal15** [Bartz24/SkyResources#51]
In my test world, I placed a rock crusher and gave it a grinder. The grinder is slowly being used to produce crushed stone without any stone.

**Comment by Bartz24** [comment]
I'm not able to reproduce this....

**Comment by sp-guip** [comment]
I am able to.

**Comment by Bartz24** [comment]
are either of you on a server by chance?

**Comment by Bartz24** [comment]
able to reproduce now, looking into it

**Comment by Bartz24** [comment]
Fixed for next version
