### ISSUE TITLE
Ticking entity at com.bartz24.skyresources.events.EventHandler.onTravelToDimensionEvent(EventHandler.java:517)

### ISSUE THREAD

**Issue by a-frenzy** [Bartz24/SkyResources#53]
Not sure where to go with this one 

https://gist.github.com/frenzye/081dfb68cf9e2e752e00a16c739cc518

**Comment by Bartz24** [comment]
This issue is occuring on 1.10.2 version which is no longer supported, sorry D:

The issue seems similar to one I had on the 1.11.2 version (which was moved to Void Island Control)
