### ISSUE TITLE
Some things need to fix

### ISSUE THREAD

**Issue by ThisIsTheGitHubAccount4MUHAKL** [Bartz24/SkyResources#54]
playing survival in MC 1.11.2 , skyresources-1.6.0.jar

1: Due to void nether, there are no BLAZE's 
    how to make BREWING stand without blaze rods
2: you should add a FE ( Fu...nny Energy) generator runs with coal to produce RF
3: right click cauldron with crushed stone/netherrack do not work
4: grinding netherrack should produce somehow nether quartz
5: there should be a way to get dirty iron/gold , not just only dia/emerald
 
best regards

**Comment by Bartz24** [comment]
1: Look at the **dark matter warper** in the guide
2: Nah
3: Look at number 4/5 _otherwise_ I'll look into it
4: That's what crushed netherrack is for in the cauldron (but only quartz dust, ex: Crushed Nether Quartz from Actually Additions)
5: dirty gems are different from metals, and crushed stone can be used to get iron/gold/copper etc **dust** on the cauldron
IIRC, the guide says that crushed stone/netherrack only works if there's a metal dust.
