### ISSUE TITLE
OreDict-keyed infusion/compression/etc recipes not working

### ISSUE THREAD

**Issue by codewarrior0** [Bartz24/SkyResources#56]
`skyresources-1.6.0`

**What I did:**

I held four Rotten Flesh in my left hand, an infusion stone in my right, and I right-clicked on a birch sapling.

**What I expected:**

I expected the sapling to disappear and a Dead Bush to be dropped as an item.

**What I got:**

Bonemeal sparkles around the sapling. Continued right-clicking eventually grew the sapling into the tree.

**My analysis:**

This recipe worked in the past. When the individual crafting recipe types were consolidated into the `ProcessRecipe` and `ProcessRecipeManager`, the specific oredict handling code in each recipe type disappeared.

The Quick-Fix would be to insert specific oredict handling code into `ProcessRecipe.stacksAreValid[Multi]`.

The Serious Fix would be to change the field `ProcessRecipe.inputs` to contain either `ItemStack` or `List<ItemStack>` and replace the Strings with the results of `OreDictionary.getOres`.  This allows `stacksAreValid[Multi]` to be vastly simplified, using the same Forge `OreDictionary.itemMatches` used by `ShapedOreRecipe`. As a bonus, the JEI handlers can be simplified too.

**Comment by Bartz24** [comment]
Released a version to fix this
