### ISSUE TITLE
[1.6.3] crash while sneaking in front of liquid tanks from neotech

### ISSUE THREAD

**Issue by kreezxil** [Bartz24/SkyResources#59]
Only your mod is in the crash report, not sure if I should cross post to neotech or not. A player reported that  sneaking in front of liquid tanks is what caused it for them. I'll have to test further.

https://pastebin.com/rsDA9dqb

**Comment by Bartz24** [comment]
Hmmm, I can't really test that as I'm pretty sure that the tank has nothing to do with it.
Code for 1.6.3 (currently not on github) is checking to avoid that (at least it should), so idk how it slipped by...
