### ISSUE TITLE
1.11.2 Guide in some other language

### ISSUE THREAD

**Issue by Rodneny** [Bartz24/SkyResources#60]
after the most recent update when i open the guide for SkyResources its in a language that looks like the enchantment table letters

**Comment by dewboy3d** [comment]
MAYDAY! MAYDAY!  

Seems like a possible prank for May Day (First Day of May)?

or a bug!  I changed the date back and forward 1 day and the rpoblem disappeared. Changed it back to May 1st and it happens again.

**Comment by Bartz24** [comment]
Yup...I set the month as 4, which I thought was April...but guess not.

Took me a while to realize that was the issue since I forgot I put that in, sorry!
