### ISSUE TITLE
Just an Idea: allow rock grinder to go only in bottom slot of machine.

### ISSUE THREAD

**Issue by Wizardon777** [Bartz24/SkyResources#63]
Every time I try to automate the rock grinder machine, I get the grinder item stuck in the stone slot if I run out of stone...

**Comment by Bartz24** [comment]
Added :)

**Comment by Wizardon777** [comment]
Well... I think you broke it...
Now smooth stone goes in to the output and gets stuck there...
![2017-06-27_21 28 36](https://user-images.githubusercontent.com/22551232/27603830-186886a2-5b80-11e7-8a5e-caeb01a412f5.png)

**Comment by Bartz24** [comment]
Well...development on 1.11 has been stopped. sorry :(

**Comment by Wizardon777** [comment]
So, basically, you're abandoning an incomplete\buggy product that many people use in their pack...

I believe I can fix it myself, if you'll give me your permission to work on it.

**Comment by Bartz24** [comment]
I'm moving on from 1.11. Yes, I know it's an issue that (some) people have to deal with.  There's other ways to do it in 1.11 (mechanical user, etc). Sorry again, but some issues have solutions to avoid it.  I'm not going to go through the trouble of reverting my work environment, and I don't want others to be building the mods at this time

**Comment by Wizardon777** [comment]
Well... I do hope you'll reconsider at some point, for now I'll revert my pack to an older version of your mod until I'll find another mod who'll be capable of the same things...

Sorry for inconveniencing you, and thanks for all the hard work so far...
