### ISSUE TITLE
Bug - Not consuming input items / crash

### ISSUE THREAD

**Issue by blaaap** [Bartz24/SkyResources#65]
Pack: Modern Skyblock 1.8 hotfix
Mod version: skyresources-1.6.4.jar

Wopper mod has an item: Wooden hopper. Basically a sort of hopper without slots.

When using a chest on top of a wooden hopper into the crucible inserter -> items that should get consumed into the crucible are not used up.

Not sure if this is a bug Sky resources, but the interaction between the mods breaks something - allowing a sort of duping/infinite resources.

doing the same setup, but replacing the crucible for a chest crashes a server with the following crashlog:
https://pastebin.com/CXmwBAbY

**Comment by Bartz24** [comment]
Fixed crash
Moving wopper issue
