### ISSUE TITLE
[1.11.2] Cauldron and stone dust interaction

### ISSUE THREAD

**Issue by balbasin09** [Bartz24/SkyResources#67]
Having several mods that add metal dusts, HOLDING right-click with multiple stone dusts causes several metal dusts of the same type to appear.

After the bug happens, JEI will also bug out and display multiple of said dust in recipes needing only one.

Have not tested edge

**Comment by balbasin09** [comment]
*edge cases like holding right click with only one dust, or not holding right click and just pressing.

**Comment by Bartz24** [comment]
Ok. This will be investigated in 1.12 as 1.11.2 isn't supported anymore
