### ISSUE TITLE
 skyresource tileEntityblocks eatup all bandwidth

### ISSUE THREAD

**Issue by CatAndHorse** [Bartz24/SkyResources#69]
Each skyresource tileEntityblock cost 5KB/s constantly ， so each mid game player can eat upto 1mbps+ with about 20 machine

I saw you notify tileEntityupdate every tick even machine is not working

**Comment by CatAndHorse** [comment]
even a not working freezer cost 3Kbytes/s

**Comment by CatAndHorse** [comment]
static final int skipConst = 100;
	  int skipCounter = 0;
	public void markDirty()
	{
		if(skipCounter <= 0)
		{
			super.markDirty();
			world.notifyBlockUpdate(getPos(), world.getBlockState(getPos()), world.getBlockState(getPos()), 3);
			
			skipCounter = skipConst;
		}
		
		skipCounter -= 1;
	}



I made a temporary fix for my own server.Works fine.
By modify TileBase.java and simply skip 99% markDirty,my server come back to life again
Maybe you can temporarily  use this before your Ultimate solution is done

**Comment by Bartz24** [comment]
I made some improvements that I hope improve this
