### ISSUE TITLE
Sand leaving a ghost block

### ISSUE THREAD

**Issue by MrAmericanMike** [Bartz24/SkyResources#7]
When you try to break sand with the Stone Rock Grinder, it disappear, it doesn't drop gravel, and it leaves a ghost block in place, if you place sand again in those spots and break it by hand you get the blocks back.

Version 0.6.14 Alpha

**Comment by Bartz24** [comment]
Sandstone turns into gravel, not sand, btw.

**Comment by MrAmericanMike** [comment]
Ohh ok, thanks ;)
