### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by CluelessPhil** [Bartz24/SkyResources#70]
Instead of having to break a block and having to throw an item in the combustion. How about adding two more slot? One for the item that is being combusted and a slot for the result? Also migration for Golden Cauldron mod for Cauldron Cleaning?

**Comment by Bartz24** [comment]
Combustion can already do that, if you have the right blocks :D
The point of the combustion setup is to slowly improve the setup. Once you have access to a dropper, use that. Once you have access to a combustion collector, use that. And once you have access to a quick dropper, use that.

I'll think about support for the golden cauldron
