### ISSUE TITLE
[1.12] New Suggestion

### ISSUE THREAD

**Issue by CluelessPhil** [Bartz24/SkyResources#71]
Add IItemstack compatibly regarding CraftTweaker I.E, add a combustion recipe that wants more than one of the same item like 5 saplings. This can be done with`.onlyStack(5).transformConsume(5)` or something close to that.

**Comment by Bartz24** [comment]
Does `<minecraft:sapling> * 5` not work?

**Comment by CluelessPhil** [comment]
Hmmm, Jared didn't suggest that

**Comment by CluelessPhil** [comment]
I did this `mods.skyresources.combustion.addRecipe(<skyresources:drycactus>,[<minecraft:bone_block>, <ceramics:unfired_clay:4> * 8 ,<minecraft:leaves:*> * 8], 500);` And my worlds don't seems to load correctly but they did with out the * 8

**Comment by Bartz24** [comment]
try `<minecraft:leaves:*>` without the * so `<minecraft:leaves>` or `<minecraft:leaves:2>` or something like that.

i have a feeling it's because my recipes don't like ingredients that accept multiple things (like ore dict or wildcard metadata)

**Comment by CluelessPhil** [comment]
Ok I'll try that

**Comment by CluelessPhil** [comment]
Works thanks!
