### ISSUE TITLE
Buff Rock Cleaners/crushers

### ISSUE THREAD

**Issue by tyler489** [Bartz24/SkyResources#79]
I feel that the Rock Cleaner/crushers are not really efficient speed wise. i can easily automate cauldron cleaning which runs at around 5x the times as a cleaner. using a compressed crusher in a mech user from extra utils and i can get 3x the drops (and can add fortune) Im thinking either some sort up upgrades like Tech reborn like efficency/speed fortune maybe water generators or an advanced rock crusher or cleaner that runs faster/has built in fortune

**Comment by Timeslice42** [comment]
The rock crusher and cleaner already have fortune built-in. The guide tells you what the numbers are.
