### ISSUE TITLE
very heavy snow can't become coarse dirt

### ISSUE THREAD

**Issue by omagaalpha** [Bartz24/SkyResources#8]
minecraft 1.10 
 forge-12.18.0.2008
 sky resources 0.8.1 beta  
When I put the very heavy snow into freezer it does not become coarse dirt 
at all.
Looking at  via code when magma cream it does not become slime

But can make heavy snowball from snowball

**Comment by Bartz24** [comment]
It works.
The mini freezer takes 4 times as long as what is shown in JEI.
You need 4 very heavy snow in the freezer and when it's done it pops out the front or into an adjecent inventory.

Magma cream is working too. They just take a while.

Also, the code on github isn't up to date as I'm having trouble syncing it.

**Comment by omagaalpha** [comment]
One had not try just 4 of them ,suggest better contrast for progress bar since hard see when harder any in it which problem I had. Also JEI not work for me for very heavy to coarse dirt for me so could not know exact receipe
