### ISSUE TITLE
Bee Attractor not attracting all common bees

### ISSUE THREAD

**Issue by GHOziLINA** [Bartz24/SkyResources#82]
Good Day, Bee attractor seems not to be getting 4 of the 12 common bees.
Have recieved Forest Bee, Meadows Bee, Modest Bee, Tropical Bee, Wintry Bee ,Marshy Bee, Valiant Bee and Ender Bee
Havent gotten one of these in over 36 hours of running. Water Bee, Rocky Bee, Embittered Bee, Marbled Bee or Valiant Bee
i have gone to river and ocean biomes to try get water bee nothing.
gone to extreme hills for rocky, in the nether for Embittered Bee and had no luck.

**Comment by kristofersokk** [comment]
I agree, "extra bees" bees are not possible to get
