### ISSUE TITLE
Unable to click on any chapters within the Guide GUI

### ISSUE THREAD

**Issue by tjsd** [Bartz24/SkyResources#83]
Modpack: Modern Skyblock v2.4.2
Modversion: skyresources-2.0.23

Issue: I can use the 3 buttons when opening the guide gui (default G). But I am unable to click on any of the chapters, even when I search for a specific entry it will not show that entry on the right pane and I cannot click to activate it on the left side. 
I have tried changing gui size in minecraft to all combinations and it effects nothing.

**Comment by Bartz24** [comment]
This is something that I have not heard from anyone else, and I do not have this issue at all either
