### ISSUE TITLE
Heat Providers make no sense

### ISSUE THREAD

**Issue by taralx** [Bartz24/SkyResources#84]
Fueled heat providers, especially at the low end, seem to be completely(?) useless. A device that consumes one piece of fuel every 14 ticks regardless of size. Also the weird sqrt computation that is involved in computing how much heat you get means that the tooltips are basically not related to how things work.

Am I completely misreading the code here?

**Comment by Timeslice42** [comment]
I have yet to even find a need for anything more than the passive heat providers (i.e lava or magma blocks). Out of curiosity, what is your setup that you feel the need to use the heat provider machines?

**Comment by taralx** [comment]
I was hoping to get better than 1mB/t out of a crucible before getting access to obsidian and without having to use dangerous substances like lava or fire.

**Comment by Timeslice42** [comment]
Are your heat providers using the default config settings? From your description it certainly doesn't seem like I'll want to be making use of them any time soon.

**Comment by taralx** [comment]
As far as I know, Modern Skyblock 2 doesn't change those settings. This came from reading the code after I failed to make them work reasonably.

**Comment by Bartz24** [comment]
Changed with last commit
