### ISSUE TITLE
[Question/Issue] Copper Yield

### ISSUE THREAD

**Issue by Timeslice42** [Bartz24/SkyResources#85]
In the modpack I'm playing the yield for copper is rediculously high. Using secondus alchemical dust and a bronze/bronze condenser one pumpkin (i.e. four seeds + eight gunpowder IIRC) is yielding roughly **seven stacks** of copper ingots. This is on the order of 50 times the yield I get from iron (i.e. four rotten flesh + eight blaze powder) in the same setup.

What's the dealio, yo? Is this intentional? What are these rates generated from? Is there a way to tweak these results? Checking the config file and the minetweaker instructions didn't yield any answers that I saw.

**Comment by tyler489** [comment]
Im assuming this is modern skyblock if so then yes this is intentional

**Comment by Timeslice42** [comment]
Okay, after digging through the code it turns out the issue is threefold: the rarity for copper is set too low, the math for low rarirty ores is a bit suspect, and the rarity for all ores is hardcoded, rather than being configurable.

At the very least can we get the rarity for the ores added to the config file?

**Comment by Bartz24** [comment]
Implemented new equations for condenser recipes

Config for rarity is also available

**Comment by Timeslice42** [comment]
Thank you for this!
