### ISSUE TITLE
[Suggestion] Condenser CraftTweaker Support

### ISSUE THREAD

**Issue by davqvist** [Bartz24/SkyResources#86]
MC 1.12.1
Forge 2484
SR 2.0.23

So, I am working on a modpack and wanted to use Sky Ressources especially because of its CraftTweaker support. I am loving the options this gives to me. While editing CraftTweaker scripts I was confused to find out that basically everything can be changed except Condenser recipes. Can this be added or are there limitations that make this impossible?

**Comment by davqvist** [comment]
Thanks for that, much appreciated.
I was looking at https://github.com/Bartz24/SkyResources/blob/1.12-2.0/src/main/java/com/bartz24/skyresources/plugin/ctweaker/MTCondenserRecipe.java
but there was no way to define the speed or efficiency. How does that work then?

**Comment by Bartz24** [comment]
Thanks for catching that.
That's what happens when the one thing I don't test fails....
