### ISSUE TITLE
[suggestion] Crucible automation

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [Bartz24/SkyResources#9]
I suggest that the crucible will be able to accept shards through a hopper or have a comparator be able to tell if it has liquids or not.

**Comment by Bartz24** [comment]
A dropper can drop the shards.

**Comment by TheGuyFromTheInternet** [comment]
yes but I prefer not to rely on a timer based system. At least a comparator can signal the dropper to drop another shard or not.

**Comment by Bartz24** [comment]
ill add the comparator support

**Comment by TheGuyFromTheInternet** [comment]
Thank you :)
