### ISSUE TITLE
Crucible doesn't support non vanilla buckets

### ISSUE THREAD

**Issue by davqvist** [Bartz24/SkyResources#91]
SR 2.0.23
MC 1.12.1 (will switch to 1.12.2 in the next days)
Forge 2485

I can't get out liquids with non vanilla buckets. I tried Clay Bucket from Ceramics and Certus Bucket from Applied Fluidics with any luck. I also tried water and Crystal Fluid, both didn't work. Other Fluid Containers like TE Tanks also don't work. It would be nice if you could check for any Fluid Container.

**Comment by Timeslice42** [comment]
From what I can tell the Certus Bucket doesn't work for any in world block. I couldn't even pick up a source block of water with it.

**Comment by davqvist** [comment]
I will test, but Ceramics Clay Bucket works with most things, just not with that. Not sure if that is SR's fault or Ceramics fault.

**Comment by davqvist** [comment]
It works now but places the liquid right away in the world with the Clay Bucket, I tried several methods and couldn't get it to work. I wonder if you could have a second look.

**Comment by Bartz24** [comment]
yeah, I noticed this too. I couldn't find a quick fix, so I'll have to look into it once I have a little more time

**Comment by davqvist** [comment]
Any news on this? (issue is also btw still closed)

**Comment by Bartz24** [comment]
yeah, still not fixed. ill open the issue again
