### ISSUE TITLE
Life Injector can attack Armor Stand to get infinity health

### ISSUE THREAD

**Issue by SihenZhang** [Bartz24/SkyResources#95]
I don't know it is a bug or not. The guide say it can attack entities. So I try to put an Armor Stand on the Life Injector, and it works. I think in this way you can get infinity health without killing mobs. But I don't know whether it is what you want. So I submit this issue to ask it.

**Comment by Bartz24** [comment]
Definitely not intended...oops

**Comment by Bartz24** [comment]
Armor stands (and other things) should now take damage in the new version
